# Generated by Django 4.2.2 on 2023-07-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hackathon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
