# Generated by Django 4.2.2 on 2023-07-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hackathon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='hackthon_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.hackathon'),
        ),
    ]
