# Generated by Django 4.2.1 on 2023-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activeuser_leaderboard_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
