# Generated by Django 4.2.2 on 2023-07-05 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_reward_hackthon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
