# Generated by Django 4.2.2 on 2023-07-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_reward_user_reward_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name_plural': 'Rewards'},
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='hackthon_title',
            new_name='hackathon_title',
        ),
    ]
