# Generated by Django 4.2.2 on 2023-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reward_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='participants',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
