# Generated by Django 4.2.1 on 2023-06-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_reward_description_reward_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='name',
            new_name='hackthon_title',
        ),
    ]
