# Generated by Django 4.2.2 on 2023-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_reward_hackthon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='is_private',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
