# Generated by Django 4.2.1 on 2023-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_hackathon_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='hilighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='numbers',
            field=models.IntegerField(default='0'),
        ),
    ]
