# Generated by Django 4.2.1 on 2023-07-07 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_leaderboard_hilighted_leaderboard_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='hilighted',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='numbers',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='highlighted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='members',
            field=models.ManyToManyField(related_name='member_leaderboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
