# Generated by Django 4.2.1 on 2023-07-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_leaderboard_hilighted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='team',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
