# Generated by Django 4.2.1 on 2023-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_leaderboard_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='team',
            field=models.CharField(max_length=20),
        ),
    ]
