# Generated by Django 4.0 on 2023-06-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hackathon')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.winner')),
            ],
        ),
    ]
