# Generated by Django 4.2.1 on 2023-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hackathon_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.AddField(
            model_name='reward',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
